Login-Modal
techdenali009/fe-colgate pull request #27
Opened 2024-09-23 14:24 UTC by Aleena-4

![alreadyreg](https://github.com/user-attachments/assets/afc9e57d-f348-493a-b956-8ec42efb4bf3)
![forgotp](https://github.com/user-attachments/assets/749d84ab-8aa5-46c5-b92b-948828d5a09b)
![login](https://github.com/user-attachments/assets/9c1d3c67-727f-4c06-a8b8-6e53c151a27d)

2024-09-23 14:35 UTC, Vishnu9901 requested changes

2024-09-23 14:35 UTC, Vishnu9901 commented on src/libs/ui/src/atoms/Modal/modal.styles.css
> +  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1); /
please remove commented code

2024-09-23 14:35 UTC, Vishnu9901 commented on src/libs/ui/src/atoms/PasswordField/index.tsx
> +      {suffix && (
please give proper names to variables

2024-09-23 14:35 UTC, Vishnu9901 commented on src/libs/ui/src/atoms/RegisterModal/registerBody.tsx
> +const registerBody: React.FC<registerBodyProps> = ({ children }) => {
Please remove unused code

2024-09-23 14:35 UTC, Vishnu9901 commented on src/libs/ui/src/atoms/RegisterModal/registerHeader.tsx
> +const registerHeader: React.FC<registerHeaderProps> = ({ heading }) => {
please remove unused code

2024-09-23 14:35 UTC, Vishnu9901 commented on src/libs/ui/src/molecules/AlreadyRegisteredForm/index.tsx
> +            {...register(LoginFormEnum.Password, { required: 'This field is required' })}
move these messages to constants file

2024-09-23 14:35 UTC, Vishnu9901 commented on src/libs/ui/src/molecules/ForgotPasswordModal/index.tsx
> +  type={undefined}
pass proper button type

2024-09-23 14:35 UTC, Vishnu9901 commented on src/libs/ui/src/molecules/LoginForm/index.tsx
> +          type={undefined}
every file should be formatted

2024-09-23 14:35 UTC, Vishnu9901 commented on tailwind.config.js
> +        '31rem': '31rem',
please remove these changes

2024-09-24 10:25 UTC, Aleena-4 commented
decline this PR due to lot of merge conflicts

2024-09-24 10:25 UTC, closed without merging