Created the static pages for the about menu.
techdenali009/fe-colgate pull request #90
Opened 2024-10-10 11:21 UTC by RohithTechdenali

Created reusable components for paragraph, heading, strong text, and anchor tag.
Created the static pages for the About menu and added the About module.

![image](https://github.com/user-attachments/assets/ace8ed68-b428-4fa5-b6f8-5d3c23d6ad3e)
![image](https://github.com/user-attachments/assets/931d7223-ba0b-43eb-98c5-436c3a3c5e39)
![image](https://github.com/user-attachments/assets/dc3843d9-954a-4a81-96e6-100da3cd8176)
![image](https://github.com/user-attachments/assets/6956142b-8831-4409-9939-e2a09abe3df9)
![image](https://github.com/user-attachments/assets/7cef99c3-e11b-4eb9-8aa7-26902924d8c6)
![image](https://github.com/user-attachments/assets/bac741ef-278f-41f0-bdae-50419a634ec8)
![image](https://github.com/user-attachments/assets/5f93a4f9-6264-454b-b08e-9d1975f050b6)
![image](https://github.com/user-attachments/assets/9d83876a-c500-4158-80e1-9d71948b818a)
![image](https://github.com/user-attachments/assets/3ea696ff-89b5-453a-b44d-cb8d78afbf9f)
![image](https://github.com/user-attachments/assets/ff13ab52-db1b-41e6-b868-cd52929c77b8)
![image](https://github.com/user-attachments/assets/efae2ca1-f4f8-43ea-9fb7-d4298aaf57c8)
![image](https://github.com/user-attachments/assets/a44b561f-4b92-458b-8e6f-ec185898304f)

2024-10-10 12:15 UTC, Vishnu9901 approved these changes

2024-10-10 12:19 UTC, Vishnu9901 requested changes

2024-10-10 12:19 UTC, Vishnu9901 commented on src/routes/routes.tsx
> +import SubscriptionTerms from '@ui/organisms/About/Subscriptions';
Use lazy Loading to a above pages

2024-10-10 12:19 UTC, Vishnu9901 commented on src/routes/routes.tsx
> +import AboutModule from 'src/modules/aboutModule/aboutModule';
use lazyloading

2024-10-10 12:19 UTC, Vishnu9901 commented on src/libs/ui/src/organisms/About/ContactUs.tsx
> +import Anchor from '@ui/molecules/Anchor/Anchor';
wrap these organisms in pages and use those pages in routes page

2024-10-10 12:19 UTC, Vishnu9901 commented on src/libs/ui/src/organisms/About/ContactUs.tsx
> +import Anchor from '@ui/molecules/Anchor/Anchor';
Maintain Folder structure

2024-10-10 13:33 UTC, RohithTechdenali commented
Made the changes as requested.

![image](https://github.com/user-attachments/assets/cb30e1f1-e3aa-469b-9c0e-b5e593a5a668)
![image](https://github.com/user-attachments/assets/00a77683-dd73-4d0f-a9b3-371fe60c0ac5)
![image](https://github.com/user-attachments/assets/def9aacb-2e84-468a-bd01-cce9bb183490)

2024-10-11 06:24 UTC, Vishnu9901 commented
Hi @RohithTechdenali , Please check all page's Ui alignments, and, font styles's and padding margin should match with pcapro website. Add routing to pages from the header

- [ ] Add routing to pages from the header

- [ ]   Ui alignments, and, font styles's and padding margin should match with pcapro website

2024-10-17 06:12 UTC, Nishant8209 commented on src/pages/ContactUsPage/index.tsx
Create one ContactUsTemplate in that template call the ContactUs component and call that template in the ContactUsPage

2024-10-17 13:40 UTC, Vishnu9901 approved these changes

2024-10-17 13:40 UTC, merged