Feature/components
techdenali009/fe-colgate pull request #91
Opened 2024-10-11 07:39 UTC by vanapallimanikanta

create a component for response pca skin 
![Screenshot 2024-10-11 130504](https://github.com/user-attachments/assets/28b66c2c-9063-4811-8b3a-93904d768451)

2024-10-11 10:00 UTC, Vishnu9901 requested changes

2024-10-11 10:00 UTC, Vishnu9901 commented on src/libs/ui/src/templates/TestPageTemplate/index.tsx
> +          content="We're so sorry to hear about your experience with our BPO 5% Cleanser and want to learn more to best assist you. Our customer support team is here to help with the return process a
content should be children

2024-10-14 07:13 UTC, Vishnu9901 approved these changes

2024-10-14 07:13 UTC, merged

2024-10-14 07:14 UTC, vanapallimanikanta commented on src/libs/ui/src/templates/TestPageTemplate/index.tsx
> +          content="We're so sorry to hear about your experience with our BPO 5% Cleanser and want to learn more to best assist you. Our customer support team is here to help with the return process a
Fixed