pdp description banner
techdenali009/fe-colgate pull request #99
Opened 2024-10-17 12:55 UTC by Aleena-4

2024-10-17 13:52 UTC, Vishnu9901 requested changes

2024-10-17 13:52 UTC, Vishnu9901 commented on src/libs/ui/src/molecules/AccordianItem/index.tsx
>    title,
Please remove unused code forwardRef

2024-10-17 13:52 UTC, Aleena-4 commented
![Screenshot 2024-10-17 191116](https://github.com/user-attachments/assets/bd2c0458-3ba8-472a-8ecb-d79c61ad2394)
![Screenshot 2024-10-17 191126](https://github.com/user-attachments/assets/5a38b968-c575-403c-9fa6-73007f975c7c)
[
![Screenshot 2024-10-17 190920](https://github.com/user-attachments/assets/0a6966d8-e773-4e60-8188-503f8f3cef5d)
](url)

2024-10-17 13:54 UTC, Aleena-4 commented
![Screenshot 2024-10-17 190920](https://github.com/user-attachments/assets/bdcb2084-4c08-4ff2-a213-d45b349d1544)
![Screenshot 2024-10-17 191116](https://github.com/user-attachments/assets/a886b03d-76d5-4e76-8252-c71703864090)
![Screenshot 2024-10-17 191126](https://github.com/user-attachments/assets/360be934-6719-4464-8a21-62d99a3682f7)
![Screenshot 2024-10-17 191135](https://github.com/user-attachments/assets/d0e3f3a0-640d-4982-b17b-d41af24c37d1)

2024-10-17 13:54 UTC, Aleena-4 commented
Updated the images

2024-10-17 13:56 UTC, Vishnu9901 requested changes

2024-10-17 13:56 UTC, Vishnu9901 commented on src/libs/ui/src/molecules/VaidationModal/index.tsx
> +  ];
move this constant variable outside of the component passwordRequirements

2024-10-18 15:13 UTC, Vishnu9901 requested changes

2024-10-18 15:13 UTC, Vishnu9901 commented on src/libs/ui/src/organisms/RelatedProducts/index.tsx
> +      <div className='pt-20 lg:px-4 '>
Remove MarketingBannerTwo sesction from Releated Products component

2024-10-21 11:39 UTC, closed without merging

2024-10-21 11:39 UTC, Aleena-4 commented
Closed due to merge conflicts